---
title: "OOI Join by URL"
author: "Kate Morkeski"
date: "2021-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) #need tidyverse for %>% and dplyr
library(httr)
library(readxl)

```

Accessing OOI data from Alfresco

```{r}

url <- ('https://alfresco.oceanobservatories.org/alfresco/webdav/OOI/Coastal%20Pioneer%20Array/Cruise%20Data/Pioneer-09_AR24_2017-10-22/Ship%20Data/Water%20Sampling/Pioneer-09_AR24_Chlorophyll_Sample_Data_2020-03-27_ver_1-00.xlsx')

```


```{r}

#problem: if this chunk and the one above are not run separately, get Error in (function (srcref) : unimplemented type (29) in 'eval'
httr::GET(url, authenticate("guest", "guest"), write_disk(tf <- tempfile(fileext = ".xlsx")))

tf

```
Reading in Excel file from Alfresco and formatting cruise ID and column headers
```{r}

ar24ooi <- read_excel(tf, 1L) 

ar24ooi$Cruise <- gsub("-", "", ar24ooi$Cruise)

ar24ooi <- ar24ooi %>% 
  rename (cruise = Cruise, 
          date = Date,
          cast = Cast, 
          niskin = Niskin, 
          replicate = Replicate,
          depth_rep = "Water Depth Rep",    #renamed variable without space
          filter_id_ooi = "Filter Sample",  #renamed variable without space 
          filter_size_ooi = "Filter Size",  #renamed variable without space
          chl_ooi = "Chl ug_per_L" ,     #renamed variable without space
          phaeo_ooi = "Phaeo ug_per_L"  #renamed variable without space
          ) %>%
  
  mutate(chl_ooi_r = round(chl_ooi, 3)) %>%
  mutate(phaeo_ooi_r = round(phaeo_ooi, 3)) %>%
  mutate(niskin = as.character(niskin)) %>%

  select(-"Station Depth", 
         -"Trip Depth", 
         -"Brown Bottle", 
         -"Vol Filt", 
         -"Vol Extracted", 
         -Sample, 
         -"90% Acetone", 
         -"Dilution During Reading", 
         -"Chl_Cal_Filename", 
         -"tau_Calibration", 
         -"Fd_Calibration", 
         -Rb, 
         -Ra, 
         -blank, 
         -Rb_blank, 
         -Ra_blank, 
         -"Lab Notebook number and page", 
         -Cal_Date, 
         -Fluorometer,
         -chl_ooi,
         -phaeo_ooi
         ) 
 

# hard code to correct error in entered niskin
ar24ooi <- ar24ooi %>% 
 mutate(
   niskin = ifelse(cruise == "AR24C" & filter_id_ooi=="02/02", 
                   yes = 4, 
                   no = ar24ooi$niskin)) 
 ar24ooi <- ar24ooi %>% 
  mutate(
    niskin = ifelse(cruise == "AR24C" & filter_id_ooi=="02/03", 
                   yes = 5, 
                   no = ar24ooi$niskin)) 
  ar24ooi <- ar24ooi %>% 
    mutate(
      niskin = ifelse(cruise == "AR24C" & filter_id_ooi=="02/04", 
                   yes = 6, 
                   no = ar24ooi$niskin)) 

ar24ooi <- ar24ooi %>% 
   mutate(
        niskin = ifelse(cruise == "AR24C" & filter_id_ooi=="02/06", 
                   yes = 8, 
                   no = ar24ooi$niskin)) 

ar24ooi <- ar24ooi %>% 
   mutate(
        niskin = ifelse(cruise == "AR24C" & filter_id_ooi=="03/04", 
                   yes = 8, 
                   no = ar24ooi$niskin)) 
   
   
filtercheck <- filter(ar24ooi, filter_size_ooi == 0)
nrow(filtercheck)
ar24ooi$filter_size_ooi <- ">0"
#this works when all filter sizes are >0, but in case a different filter size is used, this needs to instead have: for the length of the data table, if NA in chl, replace the value.


```
Read in cruise data from API and format to enable join. 
```{r}
ar24a <- read_csv("https://nes-lter-data.whoi.edu/api/chl/ar24a.csv")
ar24b <- read_csv("https://nes-lter-data.whoi.edu/api/chl/ar24b.csv")
ar24c <- read_csv("https://nes-lter-data.whoi.edu/api/chl/ar24c.csv")

# API excludes bucket sample from AR24B

#AR24B cast 4 hard code output from API before join to accommodate combined bottles 4-6 and 9-10
ar24b <- ar24b %>%
  mutate(niskin = ifelse(ra == 147.6 | ra == 151.8, "4-6", niskin), 
         niskin = ifelse(ra == 108.7 | ra == 102.5, "10-12", niskin))

ar24abc <- rbind(ar24a, ar24b, ar24c)

ar24abc <- ar24abc %>% 
  mutate(chl_r = round(chl, 3)) %>% 
  mutate(phaeo_r = round(phaeo, 3)) %>% 
  select(-vol_filtered, -tau_calibration, -fd_calibration, -rb, -ra, -blank, -rb_blank, -ra_blank, -chl, -phaeo)

# add method_contributor column
ar24abc <- ar24abc  %>% 
    mutate(method_contributor  = case_when(filter_size=="<10" ~ "method_Sosik",         
                                           filter_size==">5" ~ "method_Rynearson", 
                                           filter_size==">20" ~ "method_Rynearson", 
                                           filter_size==">0" ~ "method_Sosik")) 
```

Join Alfresco and API data. 
```{r}
ar24all <- full_join(ar24ooi, ar24abc, by = c('cruise','cast','niskin','replicate'))

ar24all <- ar24all %>% mutate(chl_diff = chl_ooi_r - chl_r)

# first check for missing values from the API for which OOI provided data
missingAPI <- filter(ar24all, is.na(chl_r))

# from the respective OOI columns: populate the filter_size, chl_r, phaeo_r
ar24all <- ar24all %>%
    mutate(
        filter_size = ifelse(is.na(filter_size), 
        yes = ar24all$filter_size_ooi, 
        no = ar24all$filter_size))  %>% 
    mutate(
        chl_r = ifelse(is.na(chl_r), 
        yes = ar24all$chl_ooi_r, 
        no = ar24all$chl_r))  %>% 
    mutate(
        phaeo_r = ifelse(is.na(phaeo_r), 
        yes = ar24all$phaeo_ooi_r, 
        no = ar24all$phaeo_r))  
# note that OOI, like Menden-Deuer group, reports NA when data not good quality

# populate method_contributor based on filter_size
ar24all <- ar24all  %>% 
    mutate(method_contributor  = case_when(filter_size=="<10" ~ "method_Sosik",         
                                           filter_size==">5" ~ "method_Rynearson", 
                                           filter_size==">20" ~ "method_Rynearson", 
                                           filter_size==">0" ~ "method_Sosik")) 

# better to populate date from bottle file to include time
# from bottle file: populate date, latitude, longitude, depth

# if the number of rows in table "all" exceeds the number of rows in "abc"
# by more than the number of rows in "missingAPI"
# then something is repeating and needs hard-coding
nrow(ar24all)-nrow(ar24abc)-nrow(missingAPI)

# then check for mismatches which will require hard coding
mismatch <- filter(ar24all, chl_diff > 0 | chl_diff < 0)
# hard coding will include when water was combined from more than 1 niskin


# write.csv(ar24all, 'ar24allqc.csv', row.names=FALSE)

```

Prepare for join with all other transect data

```{r}

# add project_id based on filter_id_ooi. if it exists, project id is ooi. if not, project id is lter
# make columns match nes-lter-chl-transect
ar24all <- ar24all %>%
  mutate(project_id = case_when(!is.na(filter_id_ooi) ~ "OOI",
                                is.na(filter_id_ooi) ~ "LTER")) %>%
  select(-date.x, 
         -depth_rep, 
         -filter_size_ooi, 
         -chl_ooi_r, 
         -phaeo_ooi_r,
         -chl_diff,
         -Comments) %>%
  rename(date = date.y,
         chl = chl_r,
         phaeo = phaeo_r)
#%>%
 # mutate(cast = as.character(cast)) 

# define headers for columns in desired order
headers_ooi <- c("cruise", "cast", "niskin", "date", "latitude", "longitude", "depth", "method_contributor", "replicate","filter_id_ooi", "filter_size",  "chl", "phaeo", "project_id")
# reorder columns as necessary
ar24all <- ar24all[, headers_ooi]


```

## Fill missing bottle metadata for those bottles sourced from Alfresco and not from API

```{r}

# columns date, latitude, longitude, and depth for AR24B hard coded 4-6 from bottle 4 only, 9-10 from bottle 9 only

# missingAPI 4 rows to populate columns date, latitude, longitude, and depth
cruiselist <- unique(missingAPI$cruise) # to pull bottle summary from API.
# define source for functions developed for the EDI packaging workflow
source("edi-utilities.R") # Dependency edi_utilities.R in repo
# compile the bottle summary
ctd_bottle_summary <- read_from_api(type = "summary", cruises = cruiselist)

# can only fill missingAPI AR24B cast 7 niskin 6 (2017-10-29 14:54:24 40.13567 -70.77450 38.443063)
# missingAPI AR24B cast 9 will require hard coding from ar24b009b.btl 
# see Sosik lab file 20171028_AR24B_bottle_summary_table.mat
# in future this could be served through REST API with "corrected" ar24b_ctd_bottle_summary.csv

cast7niskin6 <- filter(ctd_bottle_summary, cast == 7 & niskin == 6)
cast7niskin6 <- cast7niskin6 %>% 
  rename (date76 = date,
          latitude76 = latitude, 
          longitude76 = longitude, 
          depth76 = depth)
cast7niskin6$niskin <- as.character(cast7niskin6$niskin)
ar24temp <- full_join(ar24all, cast7niskin6, by = c('cruise','cast','niskin'))

# from the respective columns: populate date, latitude, longitude, and depth
ar24temp <- ar24temp %>%
    mutate(
        latitude = ifelse(is.na(latitude), 
        yes = ar24temp$latitude76, 
        no = ar24temp$latitude))  %>% 
    mutate(
        longitude = ifelse(is.na(longitude), 
        yes = ar24temp$longitude76, 
        no = ar24temp$longitude))  %>% 
    mutate(
        depth = ifelse(is.na(depth), 
        yes = ar24temp$depth76, 
        no = ar24temp$depth))  
# can't quite figure out syntax for replacing date above
#     mutate(
#       date = as.Date(ifelse(is.na(date), origin = "1970-01-01"))
#       yes = ar24temp$date76, 
#       no = ar24temp$date))  %>%
ar24all <- ar24temp %>%
  select(-date76, 
         -latitude76,
         -longitude76,
         -depth76)


# write csv file 
write.csv(ar24all, 'ar24.csv', row.names=FALSE)
```

